name: Auto Update Playlists

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Run update script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_API_KEY_2: ${{ secrets.YOUTUBE_API_KEY_2 }}
          YOUTUBE_API_KEY_3: ${{ secrets.YOUTUBE_API_KEY_3 }}
          YOUTUBE_API_KEY_4: ${{ secrets.YOUTUBE_API_KEY_4 }}
          YOUTUBE_API_KEY_5: ${{ secrets.YOUTUBE_API_KEY_5 }}
        run: node scripts/auto-update.js

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update playlists [skip ci]"
          file_pattern: "server/data/**/*.json"
